force-app/main/default/objects/Country_codes__c/Country_codes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Country codes</label>
</CustomObject>

force-app/main/default/objects/Country_codes__c/fields/Code_Number__c.field-meta.xml
<CustomField>
    <fullName>Code_Number__c</fullName>
    <label>Code Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VFCountryCode_CX.cls
public with sharing class VFCountryCode_CX {

   public string selectString {get; set;}
   public string contryCode {get; set;}
   public VFCountryCode_CX (ApexPages.StandardController controller) {

  }
  public list<selectoption> getcontriesoption(){
  list<selectoption> countryOption= new list<selectoption>();

  map<string, Country_Codes__c> countrycodemap = Country_Codes__c.getAll();
  countryOption.add(new selectoption('', '__None__'));

  for(string countryName  :countrycodemap.keyset()){
  string cLabel = CountryName;
  string value = countrycodemap.get(countryName).Code_Number__c;

  countryOption.add(new selectoption(value , cLabel ));
  }
  return countryOption;
   }

}