force-app/main/default/objects/Cricket__c/Cricket__c.object-meta.xml
<CustomObject>
    <label>Cricketer</label>
    <nameField>
        <displayFormat>CRIT-{0000}</displayFormat>
        <label>Cricketer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cricketers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cricket__c/fields/Cricketer_Name__c.field-meta.xml
<CustomField>
    <fullName>Cricketer_Name__c</fullName>
    <label>Cricketer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cricket__c/fields/Image_url__c.field-meta.xml
<CustomField>
    <fullName>Image_url__c</fullName>
    <label>Image url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Cricket__c/fields/Images__c.field-meta.xml
<CustomField>
    <fullName>Images__c</fullName>
    <formula>IMAGE ( Image_url__c , Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Images</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cricket__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>West indies</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cricketResultProvider.cls
public with sharing class cricketResultProvider {
    
    @AuraEnabled(cacheable=true)
    public static list<Cricket__c> cricketResultProviderMethod(String nationalPicApex){
        system.debug('nationalPicApex='+nationalPicApex);
        if (String.isBlank(nationalPicApex)) {
            return [SELECT Id, Cricketer_Name__c, Images__c, Image_url__c, Nationality__c, Run__c FROM Cricket__c];
        } else {
            return [SELECT Id, Cricketer_Name__c, Images__c, Image_url__c, Nationality__c, Run__c FROM Cricket__c WHERE Nationality__c = :nationalPicApex];
        }
    }

    @AuraEnabled(cacheable=true)
     public static Cricket__c  updateCricket(Cricket__c objacc){
      try {
         update objacc;
         return objacc;
      } catch (Exception e) {
         throw new AuraHandledException(e.getMessage());
      } 
    }
}