force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>APID-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/True_Verification__c.field-meta.xml
<CustomField>
    <fullName>True_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>True Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch2AddresCityPuneUpdt.cls
global class Batch2AddresCityPuneUpdt implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQuerylocator('select Country__c, State__c, City__c from Address__c where City__c !=\'Pune\' and Applicant__r.Gender__c=\'Male\' and Applicant__r.True_Verification__c=true');
		}
	global void execute(Database.BatchableContext BC, list<Address__c> adrlist){
		 if(!adrlist.isEmpty()){
		 for(Address__c objadr : adrlist){
		 objadr.Country__c='Shrilnaka';
		 objadr.State__c='Punjab';
		 Objadr.City__c='Pune';
		 }
		 Database.Update(adrlist, false);
		 }
		}
	global void finish(Database.BatchableContext BC ){

	}
}