force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>APID-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/List_Of_Address__c.field-meta.xml
<CustomField>
    <fullName>List_Of_Address__c</fullName>
    <label>List Of Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Police_verification__c.field-meta.xml
<CustomField>
    <fullName>Police_verification__c</fullName>
    <formula>IF( Age__c &gt;=18, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Police verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAddresToApplicant.cls
global class BatchAddresToApplicant implements Database.Batchable<sObject>{
    
   global Database.QueryLocator start(Database.BatchableContext BC){
  return database.getQueryLocator('select Id,Name,City__c,Pin_Code__c,Applicant__r.Id,Applicant__r.Name,Applicant__r.Police_verification__c from Address__c where City__c=\'Nagpur\' and Pin_Code__c like \'44%\' and Applicant__r.Police_verification__c=true');
  }
    
  global void execute(Database.BatchableContext BC, list<Address__c> Addrlist){
    set<Id> appidset = new set<id>();
			if(!Addrlist.isEmpty()){
			for(Address__c objadr : Addrlist ){
			if(objadr.Applicant__c !=null){
			  appidset.add(objadr.Applicant__c);
			}
		  }
		}
		  
    Map<Id, Applicant__c> Appmap = new Map<Id, Applicant__c>();
			if(!appidset.isEmpty()){
			for(Applicant__c objapp : [select Id,Name,Police_verification__c, List_Of_Address__c from Applicant__c where Id IN : appidset]){
				Appmap.put(objapp.Id, objapp);
			 }
			}
	if(!Appmap.IsEmpty()){
			   for(Address__c objadr : Addrlist){
			   if(Appmap.Containskey(objadr.Applicant__c)){
			   if(string.isBlank(Appmap.get(objadr.Applicant__c).List_Of_Address__c)){
			       Appmap.get(objadr.Applicant__c).List_Of_Address__c=objadr.Name+' '+objadr.City__c+' '+objadr.Pin_Code__c ;
			   }
			   else{
			       Appmap.get(objadr.Applicant__c).List_Of_Address__c=Appmap.get(objadr.Applicant__c).List_Of_Address__c+'\n'+objadr.Name+' '+objadr.City__c+' '+objadr.Pin_Code__c ;
			   }
	       }
	   }
        Database.update(Appmap.values(), false);
	}		
	
  }
    global void finish(Database.BatchableContext BC){
  
   }
 }