force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/pokemonClass.cls
public with sharing class pokemonClass {
   
    @AuraEnabled(cacheable=true)
    public static list<Pokemon__c> getPokemonlist(String searchKey) {
      if(searchKey != ''){
         String searchPokemon = '%'+searchKey+'%';
         list<Pokemon__c> pokemonSearchList = [Select ID,Name,Image_url__c,Image__c, Height__c, Weight__c,Trainer__r.Name from Pokemon__c where Name  LIKE : searchPokemon];
         return pokemonSearchList;
      } 
      else{
         list<Pokemon__c> pokemonList = [Select ID,Name,Image_url__c,Image__c, Height__c, Weight__c,Trainer__r.Name from Pokemon__c ];
         return pokemonList;
      }
   }
}