force-app/main/default/objects/Contact/fields/Contact_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Contact_Relationship__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Relationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Contact Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Relationship__c/fields/Con_ID__c.field-meta.xml
<CustomField>
    <fullName>Con_ID__c</fullName>
    <label>Con ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/fields/Con_Name__c.field-meta.xml
<CustomField>
    <fullName>Con_Name__c</fullName>
    <label>Con Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConRelationClass.cls
public class ConRelationClass {

    list<Contact_Relationship__c> listcon = new list<Contact_Relationship__c>();
    
    public void GetConMethod(list<contact> conlist){
        for(contact objcon : conlist){
            if(objcon.Contact_Relationship__c==true){
                Contact_Relationship__c objh = new Contact_Relationship__c();
                  objh.Con_Name__c=objcon.FirstName;
                  objh.Con_ID__c=objcon.Id;
                listcon.add(objh);
            }
        }
        insert listcon;
    }
}