force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>( TODAY() - DOB__c )/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Passport_message__c.field-meta.xml
<CustomField>
    <fullName>Passport_message__c</fullName>
    <label>Passport message</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch1ApplicPassmessASSI1.cls
global class Batch1ApplicPassmessASSI1 implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
     return Database.getQueryLocator('select Id,Age__c,Passport_message__c from Applicant__c where Age__c<=18 ');
    }
    global  void execute(Database.BatchableContext BC, list<Applicant__c> applist){
        if(!applist.isEmpty()){
            for(Applicant__c objapp : applist){
                objapp.Passport_message__c='Your Passport Has Been Rejectd';
             }
            Database.update(applist, false);
          }
     }
    global void finish(Database.BatchableContext BC){
       Database.executeBatch(new Batch2PassportRejEmailSendASS1());
    }
}