force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchLec58Story2APPLI.cls
global class BatchLec58Story2APPLI implements database.Batchable<sObject>{

global database.querylocator start(database.batchablecontext BC){
       return database.getquerylocator('select Id, First_Name__c, Last_Name__c ,Email_Id__c from Applicant__c where Email_Id__c!=null ');
      }
global void execute(database.batchablecontext BC, list<Applicant__c> applist){
        List<Messaging.SingleEmailMessage> maillist = new List<Messaging.SingleEmailMessage>();
            if(!applist.isempty()){
            for(Applicant__c objapp : applist){
            messaging.SingleEmailMessage mail= new messaging.SingleEmailMessage();
                        mail.setToAddresses(new string[] {objapp.Email_Id__c});
                        mail.setsenderdisplayName('Anshul sahare');
                        mail.setsubject('HAPPY DIWALI');
                        mail.setplaintextbody('HII Mr'+objapp.First_Name__c+' '+objapp.Last_Name__c+'\n'+'HAPPY DIWALI you and your family...!!'  );
                        maillist.add(mail);
                    }
                }
            
            if(!maillist.isEmpty()){
                messaging.sendEmail(maillist,false);
            }
            }
          
global void finish(database.BatchableContext BC){
    
    }
}