force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>( TODAY() - DOB__c )/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Passport__c/Passport__c.object-meta.xml
<CustomObject>
    <label>Passport</label>
    <nameField>
        <displayFormat>PID-{00000}</displayFormat>
        <label>Passport ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passport</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passport__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Passport</relationshipLabel>
    <relationshipName>Passport</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Passport__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>reject</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch2PassportRejEmailSendASS1.cls
global class Batch2PassportRejEmailSendASS1 implements Database.Batchable<sObject> {
  
    global Database.QueryLocator start(Database.BatchableContext BC){
     return Database.getQueryLocator('select Status__c from Passport__c where Applicant__r.Age__c<=18'); 
    }
    global void execute(Database.BatchableContext BC,list<Passport__c> passlist){
        if(!passlist.isEmpty()){
            for(Passport__c objpass : passlist){
                objpass.Status__c='reject';
            }
            Database.update(passlist, false);
        } 
    }
     
    global void finish(Database.BatchableContext BC){
        list <messaging.SingleEmailMessage> maillist = new list<messaging.SingleEmailMessage>();
        messaging.SingleEmailMessage mail =new messaging.SingleEmailMessage();
                mail.setToAddresses(new String[] {'Applicant__c'});
                mail.setSenderDisplayName('Anshul Sahare');
                mail.setSubject('welcome to account');
                mail.setPlainTextBody('Your Status Has Been Rejeted');
                maillist.add(mail);
    }
}