force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/True_Verification__c.field-meta.xml
<CustomField>
    <fullName>True_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>True Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch1AppliMaleUpdate.cls
global class Batch1AppliMaleUpdate implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC){
     return Database.getQueryLocator('select Id,Gender__c,True_Verification__c from Applicant__c where Gender__c=\'Male\' and True_Verification__c !=true');
		}
	global void execute(Database.BatchableContext BC, list <Applicant__c> applist){
        if(!applist.isEmpty()){
		for(Applicant__c objapp : applist){
		if(string.isNotBlank(objapp.Gender__c)){
		    objapp.True_Verification__c=true;
		  }
		}
		Database.Update(applist, false);
	 }
  }
	global void finish(Database.BatchableContext BC){
     Database.executeBatch(new Batch2AddresCityPuneUpdt());
	}
}