force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/True_Verification__c.field-meta.xml
<CustomField>
    <fullName>True_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>True Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAppliacntPoliceUpdtTEST.cls
@isTest
public class BatchAppliacntPoliceUpdtTEST {

    @testSetup
    public static void setup(){
        list<Applicant__c> applist = new list<Applicant__c>();
        for(integer i=1; i<200; i++){
            Applicant__c objapp = new Applicant__c(First_Name__c='Rawan', Gender__c='Male', Phone_Number__c='123456789');
            applist.add(objapp); 
        }
        if(!applist.isEmpty()){
            database.insert(applist, false);
        }
    }
    @isTest
    public static void testbatchappUpdate(){
        test.startTest();
             database.executeBatch(new BatchAppliacntPoliceUpdt(), 200);
        test.stopTest();
        
        list<Applicant__c> actualAPPlist = [select Id,First_Name__c,Gender__c,Phone_Number__c, True_Verification__c from Applicant__c ];
        for(Applicant__c actualobjAPP : actualAPPlist ){
            system.assertEquals(true, actualobjAPP.True_Verification__c);
        }
    }
}