force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/True_Verification__c.field-meta.xml
<CustomField>
    <fullName>True_Verification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>True Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAppliacntPoliceUpdt.cls
global class BatchAppliacntPoliceUpdt implements database.Batchable<sObject> {

   global Database.QueryLocator start(database.BatchableContext BC){
   string Appstring = 'select Id,First_Name__c,Gender__c,True_Verification__c from Applicant__c where True_Verification__c!=true and Gender__c=\'Male\'';
       return database.getQueryLocator(Appstring);
    }
    global void execute(database.BatchableContext BC, list<Applicant__c> applist){
        if(!applist.isEmpty()){
            for(Applicant__c objapp : applist){
                if(string.isNotBlank(objapp.Gender__c)){
                    objapp.True_Verification__c=true;
                }
            }
            database.update(applist, false);
        }
    
    }
    global void finish(database.BatchableContext BC){
        
    }
}