force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/wrapperexample2.cls
public class wrapperexample2 {
 
 list<Applicant__c> appList = new list<Applicant__c>();
 list<Account> accList = new list<Account>();
 list<wrapper> lstw = new list<wrapper>();
 
 public list<wrapper> getlstWrapperString(){
  
  appList=[select Id,First_Name__c, Last_Name__c, Gender__c from Applicant__c LIMIT 10];
  accList=[select Name, Rating, Id from Account];
  
  for(integer i=0; i<appList.size(); i++){
   lstw.add(new wrapper(appList[i].First_Name__c,appList[i].Last_Name__c,appList[i].Gender__c,accList[i].Name,accList[i].Rating ));
  }
  return lstw;
 }
 
 public class wrapper{
   public string FName{get; set;}
   public string LName{get; set;}
   public string GenderAppli{get; set;}
   public string AccName{get; set;}
   public string AccRating{get; set;}
   
   public wrapper(string FName,string LName,string GenderAppli,string AccName,string AccRating){
     this.FName=FName;
     this.LName=LName;
     this.GenderAppli=GenderAppli;
     this.AccName=AccName;
     this.AccRating=AccRating;
   }
 }
 
 
 
}